### ISSUE TITLE
bundle protobuf c++ library

### ISSUE THREAD

**Issue by mikejiang** [eddelbuettel/rprotobuf#1]
We (@gfinak , @raphg and I)  are currently planning to deprecate 'boost serialization library' with 'protobuf c++ (>=2.6.0)' for our package [flowWorkspace](https://github.com/RGLab/flowWorkspace/tree/multiMessages) 

It will be nice for `RProtobuf` to bundle `protobuf` c++ library so that other packages can simply compile and link against it instead of adding the installation burden to the package users who don't necessarily have `admin permission` and the knowledge of setting `environment variable properly` (e.g. `PATH` and `LD_LIBRARY_PATH`).

**Comment by mikejiang** [comment]
Just so you know that we did end up bundling `libprotobuf`(no need for `pb` compiler) in our own [package](https://github.com/RGLab/flowWorkspace) after various compiling,linking and running-time issue related `pb` library reported from the package users.

**Comment by eddelbuettel** [comment]
I appreciate the update.  If you think you can distill a lesson on how to wrap a library, that might be of interest to folks.
