### ISSUE TITLE
Prepare release before 3.3

### ISSUE THREAD

**Issue by jeroenooms** [eddelbuettel/rprotobuf#10]
The `makevars.win` file needed some [changes](https://github.com/eddelbuettel/rprotobuf/commit/04e38a4128f18c8f9b7c276785ee568a17a38df9) to support the new toolchain on windows. CRAN would appreciate a new release, at least before R 3.3 is released but preferably sooner..

**Comment by eddelbuettel** [comment]
Probably true for other packages (RQuantLib ?) too, no?

**Comment by jeroenooms** [comment]
I think we already took care of `RQuantLib` on the server.

**Comment by jeroenooms** [comment]
It seems like you waited too long with this and CRAN has blacklisted `RProtoBuf` on the win builder.

**Comment by eddelbuettel** [comment]
It worked with win-builder yesterday or else I would not have released.

**Comment by jeroenooms** [comment]
OK we'll see if they re-appear on CRAN. It look like at least cmd checks have been disabled for windows.

**Comment by eddelbuettel** [comment]
Yes, thanks -- I just sent CRAN / Uwe an email to turn this back on.  Thanks for your work on this; I also added ChangeLog and NEWS entries for it.   Our hands were somewhat tied as we waited to JSS to come through.   In hindsight an April release would have been fine.  Oh well -- not sure exactly how many people use this on Windoze.
