### ISSUE TITLE
Does ServiceDescriptor__method routine exist?

### ISSUE THREAD

**Issue by MichaelChirico** [eddelbuettel/rprotobuf#101]
https://github.com/eddelbuettel/rprotobuf/blob/0c40beaf06fe2838322569fe33fc33d6bd6e30cb/R/00classes.R#L291

```r
get0("ServiceDescriptor__method", asNamespace("RProtoBuf"), ifnotfound=FALSE)
# [1] FALSE
```

It looks like maybe "not yet implemented"?

https://github.com/eddelbuettel/rprotobuf/blob/0c40beaf06fe2838322569fe33fc33d6bd6e30cb/src/init.c#L319

Maybe that default case should be `stop()` instead?

(found by looking for remaining hits of [`routine_registration_linter()`](https://lintr.r-lib.org/reference/routine_registration_linter.html))

**Comment by eddelbuettel** [comment]
Please check ChangeLog, NEWS, github commits -- as I recall there was a case of something missing somewhere and I may have left a note for context.

**Comment by MichaelChirico** [comment]
I haven't searched commits but there's nothing in ChangeLog/NEWS:

https://github.com/search?q=repo%3Aeddelbuettel%2Frprotobuf%20%2FServiceDescriptor__method%2F&type=code

**Comment by eddelbuettel** [comment]
I have a vague recollection that with this (one) commented-out function it ends up either in a build-time ("no symbol" ?) or run-time pothole. If you want to fix it to make it better I would welcome PRs.

**Comment by MichaelChirico** [comment]
> I have a vague recollection that with this (one) commented-out function it ends up either in a build-time ("no symbol" ?) or run-time pothole. If you want to fix it to make it better I would welcome PRs.

If I'm reading it correctly, removing quotes would give the build-time (or probably just `R CMD check`) error about undefined symbol, but with quotes, it would wait till runtime to look up the routine & then fail.
