### ISSUE TITLE
User-friendly suggestion for missing-dependency configure failure

### ISSUE THREAD

**Issue by Fifis** [eddelbuettel/rprotobuf#105]
Obviously RProtoBuf depends on Protobuf being available on the system. Usually, installing the corresponding `-dev` library on Debian-based system works. However, installing `libprotobuf-dev` and `protobuf-compiler` is not sufficient in this case. One has to check file lists for various packages to find that it is `libprotoc-dev` that provides `google/protobuf/compiler/code_generator.h`.

Suggestion: it is considered good user experience to list the dependencies as a suggestion if `configure` fails, e.g.:

```r
Make sure that the development headers and other Protobuf dependencies are installed.
For Debian-based systems: apt install libprotobuf-dev protobuf-compiler libprotoc-dev
```

That should save time for the users who are wondring why doing `libprotobuf-dev` did not change anything.

**Comment by eddelbuettel** [comment]
This is an R package, and R packages usually communicate this via the `SystemRequirements` field in file `DESCRIPTION`:

https://github.com/eddelbuettel/rprotobuf/blob/ba788142263a2cad1829d40d4c0dc425b23f96c7/DESCRIPTION#L18-L21

**Comment by Fifis** [comment]
Thank you, I did not know this. Some popular packages handle `configure` errors at the time of installation, which is why I thought that it would be a good idea. Another reason was, there is a [similar answer on SO](https://stackoverflow.com/a/49581387) that does not list `libprotoc-dev` for a different package that also relies on protobuf. Closing the issue.
