### ISSUE TITLE
Error in new(): no slot of name "virtual" for this object of class "Descriptor"

### ISSUE THREAD

**Issue by clocklear** [eddelbuettel/rprotobuf#12]
Following along with the intro vignette, it seems that no matter which proto I try to instantiate, there is an underlying issue with class creation:

```
> p <- new( tutorial.Person, name = "Romain", id = 1 )
Error in new(tutorial.Person, name = "Romain", id = 1) : 
  no slot of name "virtual" for this object of class "Descriptor"
```

Have you seen this before?  Is this due to a version mismatch of some sort?  I've tried the tutorial protos (proto2) as well as my own implementations (proto3) -- nothing seems to work.

**Comment by eddelbuettel** [comment]
Well that would certainly trip up the unit tests.  So let's start with the _very_ first step: did you actually run `library(RProtoBuf)` ?   This, by our convention, loads the demo proto file so this works for me:

```r
R> library(RProtoBuf)
R> p <- new( tutorial.Person, name = "Romain", id = 1 )
R> p
message of type 'tutorial.Person' with 2 fields set
R> 
```

**Comment by clocklear** [comment]
Welp, now I feel sheepishly idiotic.  I did not `library(RProtoBuf)`.  I was naively under the assumption that `library()` only brought things into the global namespace, and was not strictly speaking required -- you could accomplish the same thing by simply specifying the package prefix.  Clearly I was wrong.  Thanks!

**Comment by eddelbuettel** [comment]
No worries. We've all been there. _Is it plugged in?_ etc pp

**Comment by eddelbuettel** [comment]
Ok -- but FWIW the original ticket here had an issue with an example which _does_ assume that a descriptor has been loaded...

**Comment by s-u** [comment]
It is loaded, but that doesn't mean that RProtoBuf is attached since you can load descriptors without attaching it. Either way, googling the error points here so I figured it's good to mention how to work around it.

**Comment by eddelbuettel** [comment]
Sure. Patches are even better.  

Just thinking out loud -- should we do something in `.onLoad()` rather than `.onAttach()`?
