### ISSUE TITLE
Error: Unsupported type

### ISSUE THREAD

**Issue by cnaumzik** [eddelbuettel/rprotobuf#14]
Hi,

I just started using protocol buffers in general and rprotobuf in particular, so this might be a really simple issue. I am currently working with the deep learning framework _caffe_ and started writing some wrapper functions in R. The model format in caffe is defined in the file _caffe.proto_ with a descriptor pool of around 60 items. I created messages for the majority of them without an issue. But for one of the descriptors, I receive an error message whenever I try to apply the `$`-operator:

`solver <- new(caffe.SolverParameter)`
`Error: Unsupported type`
`>solver$ `

In addition ( in RStudio), there is a pop-up window which states _R code execution error_.
I can, however, use the `[[`-operator. Do you have any idea on how to resolve this issue?

**Comment by eddelbuettel** [comment]
Could you possibly cook up a self-contained reproducible example?  I don;t happen to have caffe hanging around, nor do I have your data.

**Comment by cnaumzik** [comment]
Hi, thanks for the reply and sorry for the inconvenience. Unfortunately, I can't attach the caffe.proto file to this message, but the most recent version is on git: caffe/src/caffe/proto/caffe.proto 
I receive the error when using the following code: 
`readProtoFiles("~/caffe.proto")`
`caffe.SolverParameter$type`
`descriptor for field 'type' of type 'caffe.SolverParameter'`
`solver_message <- new(caffe.SolverParameter , type ="SGD")`
`solver_message$`
`Error: Unsupported type`
I use R 3.3.0 and version 0.4.4 of RProtoBuf. I normally work in RStudio but this error also shows up when running R from the cmd line.

**Comment by eddelbuettel** [comment]
The [caffe.proto file is here](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto) and is almost 1400 lines.  I am afraid someone will have to break that down.

One hunch, based on the error message: try renaming `type` to something else [on this line](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L213) as `type` is a reserved R word.

**Comment by cnaumzik** [comment]
That has fixed the issue, thank you!

**Comment by eddelbuettel** [comment]
Great, thanks for the report back.  Little nuisances like this are the price we pay for having to mock full reflectivity from inside the language.
