### ISSUE TITLE
Is there a plan to include equivalents for the Protocol Buffers delimited I/O functions in Java?

### ISSUE THREAD

**Issue by maciejlach** [eddelbuettel/rprotobuf#22]
Google lists writing message length as a varint before serializing the message itself as one of the [techniques](https://developers.google.com/protocol-buffers/docs/techniques) used for sending proto messages over a wire. For Java classes, `protoc` compiler generates convince functions for this purpose.

Do you plan to include such functionality in RProtoBuf library?

Discussion on C++ version can be found at [SO](http://stackoverflow.com/questions/2340730/are-there-c-equivalents-for-the-protocol-buffers-delimited-i-o-functions-in-ja).

**Comment by eddelbuettel** [comment]
We are open to well-written pull request, preferably with documentation and tests.

These days none of us use Protocol Buffers all that much so it is unlikely that such an extension comes form us.
