### ISSUE TITLE
Cannot read proto3 files in RStudio

### ISSUE THREAD

**Issue by bmkor** [eddelbuettel/rprotobuf#27]
RProtobuf 0.4.9
RStudio Version 1.0.136
R version 3.3.3
macOS Sierra v10.12.4

When execute function readProtoFiles in a directory containing proto3 files, the following error encounter.
```
Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
Error in readProtoFiles(dir = proto.dir) : 
```

Have I missed something? 

Hope anyone can hint/help me. Thanks a lot.

**Comment by eddelbuettel** [comment]
What OS?  What Version?  What RStudio version? 

Are you sure you have no library path shadowing things with another (older) version?

I just went into RStudio (very recent version from daily builds, Ubuntu 16,10) and without any difficulties ran
both `demo(addressbook)` as well as the code from `runit.proto3.r`.

**Comment by bmkor** [comment]
I apologise for my poor English. My bad indeed. 

My OS version etc were on the top and let me rewrite them here:

RProtobuf version 0.4.9 installed in 
RStudio Version 1.0.136 with R version 3.3.3

The above are running in my MacBook with OS: macOS Sierra v10.12.4

I got this error when I ran the proto below which I think is proto3. 
https://github.com/hyperledger/fabric/blob/master/protos/msp/identities.proto

**Comment by eddelbuettel** [comment]
That too works for me:

```r
R> library(RProtoBuf)
R> download.file("https://raw.githubusercontent.com/hyperledger/fabric/master/protos/msp/identities.proto", "/tmp/id.proto")
trying URL 'https://raw.githubusercontent.com/hyperledger/fabric/master/protos/msp/identities.proto'
Content type 'text/plain; charset=utf-8' length 1074 bytes
==================================================
downloaded 1074 bytes

R> RProtoBuf::readProtoFiles("/tmp/id.proto")      # can read the file without issues
R> Sys.getenv("RSTUDIO")                           # and I am in RStudio
[1] "1"
R> 
```

**Comment by eddelbuettel** [comment]
And yes, you did of course state your versions of R and all  that.  Sorry about that,

But maybe you built RProtoBuf against an older libprotobuf library.   It is not an issue in the package.  The package deals with proto3 just fine.  Check how you built and install RProtoBuf.

**Comment by bmkor** [comment]
Will dig out where I go wrong. Thanks a lot.

**Comment by bmkor** [comment]
Silly me. My protobuf lib not updated. Problem solved. Thanks a lot.

**Comment by eddelbuettel** [comment]
It happens, not to worry.
