### ISSUE TITLE
proto3 support on MacOS

### ISSUE THREAD

**Issue by maciejlach** [eddelbuettel/rprotobuf#30]
We have stumbled upon an issue for loading the proto3 file via rprotobuf:

```
> packageVersion('RProtoBuf')
[1] ‚0.4.9'
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/xythub/proto"
xyt/api.proto:9:10:Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
Fehler in readProtoFiles(dir = "xyt") : 
  Could not load proto file 'xyt/api.proto'
```

OS: Mac OS X 10.12.6

Is there any chance for a fix similar to: https://github.com/eddelbuettel/rprotobuf/issues/20?

**Comment by eddelbuettel** [comment]
Well in our _code_ proto3 has been supported for a long time now.  I suspect that your libproto* files may simply be stuck at version 2 so a simple rebuild should fix that.   I am not on macOS so I can't tell for sure.

**Comment by eddelbuettel** [comment]
Also see #27 which is also on macOS and which was solved by upgrading the required libproto*.

**Comment by maciejlach** [comment]
@eddelbuettel: thank you for the answer. There was a problem with old libproto*.
