### ISSUE TITLE
Macintosh install fails 

### ISSUE THREAD

**Issue by jmagosta** [eddelbuettel/rprotobuf#33]
install.packages("Rprotobuf") fails to find google specific files. Either the include path, or the install contents are lacking:

```
trying URL 'https://cran.rstudio.com/src/contrib/RProtoBuf_0.4.10.tar.gz'
...

checking google/protobuf/stubs/common.h usability... no
checking google/protobuf/stubs/common.h presence... no
checking for google/protobuf/stubs/common.h... no
configure: WARNING: Protobuf headers not found with default CXXFLAGS and CPPFLAGS, manually trying /usr/local/include
configure: WARNING: Unsetting ac_cv_header_google_protobuf_stubs_common_h
checking google/protobuf/stubs/common.h usability... no
checking google/protobuf/stubs/common.h presence... no
checking for google/protobuf/stubs/common.h... no
configure: error: ERROR: ProtoBuf headers required; use '-Iincludedir' in CXXFLAGS for unusual locations.
ERROR: configuration failed for package ‘RProtoBuf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RProtoBuf’
Warning in install.packages :
  installation of package ‘RProtoBuf’ had non-zero exit status

```

**Comment by eddelbuettel** [comment]
We just ask `pkg-config` for the values, see [here](https://github.com/eddelbuettel/rprotobuf/blob/e2df4eb35beabcc097841cca9c63954d85dde9ea/configure.ac#L27-L41).

What happens when you run that by hand?  Works here as it should:

```shell
edd@bud:~$ pkg-config --cflags protobuf
-pthread
edd@bud:~$ pkg-config --libs protobuf
-lprotobuf -pthread -lpthread
edd@bud:~$ 
```

**Comment by jmagosta** [comment]
pkg-config has no knowledge of protobuf

> $ pkg-config --cflags protobuf
Package protobuf was not found in the pkg-config search path.
Perhaps you should add the directory containing `protobuf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'protobuf' found

...The problem was that google's protoc needs to be  installed from source:


> https://github.com/google/protobuf.git

On most Macs this of course requires installing several parts of the toolchain google uses.  

Thanks -jm

**Comment by eddelbuettel** [comment]
Good catch!
