### ISSUE TITLE
Serializing a large vector of characters takes a very long time

### ISSUE THREAD

**Issue by jefshe** [eddelbuettel/rprotobuf#34]
I've noticed the following command takes a considerable amount of time to serialize to protobuf format and consumes a considerable amount of memory(~1GB):
```R
RProtoBuf::serialize_pb(ggmap::get_map('Europe',zoom=4),NULL)
```
The object being serialized is a large character vector representing a 1280x1280 image of a map.

**Comment by eddelbuettel** [comment]
Err, yeah, and?  

We dispatch pretty much directly to the C++ code so ...

**Comment by murraystokely** [comment]
Serializing binary data from get_map() won't be very efficient.  The bulk
of the returned object from get_map I believe is just a big bitmap of
pixels to display the map.

Are you using this in another language or system that you need to read back
in the object?

Protocol Buffers are much more performant if you have a custom schema
(.proto) for your data and need to share that data between different
systems.

If you really wanted to do this for a lot of maps with ggmap, then I would
look at implementing a custom .proto file for ggmap objects, and then skip
the generic serialize_pb but serialize to your specific .proto instead.
That would make sure to interpret your bitmap as raw bytes that can be
quickly copied into place in C++.

       - Murray

**Comment by jefshe** [comment]
Thanks for the input guys

**Comment by eddelbuettel** [comment]
This is a bit of a particular case:  an image (ie its matrix) could probably just be sent as a raw vector,
