### ISSUE TITLE
Binary package for el-capitan

### ISSUE THREAD

**Issue by siddharthab** [eddelbuettel/rprotobuf#35]
https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/RProtoBuf-00install.html
The el-capitan builder on CRAN is missing the protobuf library.

**Comment by eddelbuettel** [comment]
Talk to CRAN, not us.  We aren't CRAN. We upload source code, building binaries is their bit.

As much as I'd like to help, our hands are tied.
