### ISSUE TITLE
Remove invalid UTF-8 strings before serialization

### ISSUE THREAD

**Issue by jefshe** [eddelbuettel/rprotobuf#36]
When working with R packages which scrape websites, e.g. twitteR, Rfacebook

many will return javascript escaped unicode characters in their strings e.g.:
"\ud83d\ude0e" (😎 ), this confuses R which converts interprets the 2 escapes as separate characters, converting the string to "\xed\xa0\xbd\xed\xb8\x8e" which is not a valid utf-8 sequence. 

This causes protobuf to throw an error and fail to serialize the entire string, giving an error about invalid multibyte sequences.

I propose that these strings should be sanitized before serialization so that the information is preserved

**Comment by eddelbuettel** [comment]
Hm. My initial instinct would be to keep such "sanitizers" in user-space, _i.e._, with your application which has domain knowledge about its inputs, no?

**Comment by jefshe** [comment]
Yeah fair enough, this is really an issues with rjson which doesn't handle unicode surrogate pairs. Have raised an issue with the maintainer

**Comment by eddelbuettel** [comment]
Thanks, that makes sense.  I was curious how other JSON parsers cope.  Here is the two-second test with Jeroen's:

```r
> library(jsonlite)
> fromJSON("{\"str\" : \"Anaheim Ducks \\ud83d\\ude0e\"}")
$str
[1] "Anaheim Ducks 😎"

>
```

Looks better, doesn't it?

**Comment by eddelbuettel** [comment]
This very fresh R update seems relevant too: http://developer.r-project.org/blosxom.cgi/R-devel/2017/10/06#n2017-10-06

/cc @alexcb
