### ISSUE TITLE
serializing "package_version" object causes infinite recursion

### ISSUE THREAD

**Issue by jefshe** [eddelbuettel/rprotobuf#37]
The following R code causes RProtoBuf to infinitely recurse:
```R
x <- package_version("1.2")
RProtoBuf::serialize_pb(x)
```

I did some digging and it looks like when this is because when sub indexing the list, the list returns itself:

```R
x <- package_version("1.2")
identical(x,x[[1]])
> TRUE
```

this causes ```lapply(obj, rexp_obj)``` to never terminate.

Perhaps in these situations, we should call unlist?

**Comment by eddelbuettel** [comment]
The package_version object is a funny one.  For kicks, can you check what happens with these two:

```
x1 <- as.raw(x)
x2 <- format(x)
```

I presume these travel fine.  I am not quite where we'd have to go to stop the recursion.  But your suggested check is a good one.   If you have time to dig ...

**Comment by jefshe** [comment]
Just raised a PR.
The output I get:
```R
> x1 <- as.raw(x)
Error: (list) object cannot be coerced to type 'raw'
> x2 <- format(x)
> x2
[1] "1.2"
```

**Comment by eddelbuettel** [comment]
No, I meant: what happens when you try to protobuf x1 or x2. I guess x1 is out anyway...

**Comment by jefshe** [comment]
```R
> serialize_pb(format(x),NULL)
 [1] 08 00 2a 07 0a 03 31 2e 32 10 00
> unserialize_pb(serialize_pb(format(x),NULL))
[1] "1.2"
```
Ah, yep works as intended
