### ISSUE TITLE
Windows: RProtoBuf fails for large messages (64MB+)

### ISSUE THREAD

**Issue by maciejlach** [eddelbuettel/rprotobuf#41]
RProtoBuf fails on Windows, while parsing large messages with following error:
```
[libprotobuf ERROR ../../protobuf-3.0.0/src/google/protobuf/io/coded_stream.cc:207] 
A protocol message was rejected because it was too big (more than 67108864 bytes).  
To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
```

Since [protobuf 3.2](https://github.com/google/protobuf/releases/tag/v3.2.0), default parsing byte limit has been increased to 2GB. It seems that RProtoBuf on Windows uses protobuf library 3.0.0 provided by rwinlib. 

Could you please upgrade Windows build to use [protobuf 3.2](https://github.com/rwinlib/protobuf/releases/tag/v3.2.0).x+ library?

RProtoBuf version: `0.4.11`

This issue doesn't occur on Linux if libprotobuf is installed in version 3.2.x+.

**Comment by eddelbuettel** [comment]
We provide the _source_ package so you may have to provide such a beefed-up binary for Windows yourself.

**Comment by eddelbuettel** [comment]
Or else you could liaise with @jeroen and see if the prebuild Windows library can be update.  

It is used by this [function](https://github.com/eddelbuettel/rprotobuf/blob/master/tools/winlibs.R) invoked from `src/Makevars.win`.

**Comment by jeroen** [comment]
It looks like I already did a build of 3.2.0 a year ago: https://github.com/rwinlib/protobuf/releases. Not sure why we didn't upgrade here. You could try to replace `3.0.0.` with `3.2.0` in `src/Makevars.win` and `tools/winlib.R` and submit to winbuilder to try your luck.

**Comment by maciejlach** [comment]
@eddelbuettel @jeroen I have used the prebuilt 3.2.0 lib to build RProtoBuf locally and than the large messages are parsed correctly. I've linked this library in initial issue, but I was too sparse with description (sorry about that).

I've committed it to a fork: https://github.com/maciejlach/rprotobuf/commit/40bc4294195eff1f10d5eb4f0a4ef1b3a9c0b7ba.

Can I provide a PR based on this commit? 
I believe, it would be much more convenient to have this available at CRAN and at master repository. Especially for packages using a RProtoBuf as a dependency.

**Comment by eddelbuettel** [comment]
Looks like a clean change, so yes, please send a PR.

**Comment by jeroen** [comment]
OK merged :) I may try to build a new protobuf one of these days, seems like they're at 3.5.1 already.

**Comment by maciejlach** [comment]
Thank you.

**Comment by eddelbuettel** [comment]
For completeness, did anybody test this on win-builder?

**Comment by jeroen** [comment]
Yes I did. I wasn't able to build the vignettes so I used `--no-build-vignettes` but other than that it passes on win builder.
