### ISSUE TITLE
Error when using proto3 syntax

### ISSUE THREAD

**Issue by rtjohn** [eddelbuettel/rprotobuf#44]
Despite installing the latest version from Google here:
https://github.com/google/protobuf/releases
`$ protoc --version`
libprotoc 3.5.1

I am getting an error when trying to read proto3 files.
The proto3 file I'm trying to read in is added as a comment below.

#### System Info
`> Sys.info()
                                                                                          sysname 
                                                                                         "Darwin" 
                                                                                          release 
                                                                                         "17.5.0" 
                                                                                          version 
"Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64" 
                                                                                         nodename 
                                                                 "XXXXXXX-Macbook-Pro.local" 
                                                                                          machine 
                                                                                         "x86_64" 
                                                                                            login 
                                                                                    "XXXXXXXX" 
                                                                                             user 
                                                                                    "XXXXXXXX" 
                                                                                   effective_user 
                                                                                    "XXXXXXXX"`

#### Install Package
`install.packages('RProtoBuf')`
`library(RProtoBuf)`

#### Vignette Example (all use proto2 syntax)
`pdir <- system.file("proto", package = "RProtoBuf")`
`pfile <- file.path(pdir, "addressbook.proto")`
`readProtoFiles(pfile)`

#### List the message descriptors
`ls("RProtoBuf:DescriptorPool")`
[1] "rexp.CMPLX"                   "rexp.REXP"                   
[3] "rexp.STRING"                  "rprotobuf.HelloWorldRequest" 
[5] "rprotobuf.HelloWorldResponse" "tutorial.AddressBook"        
[7] "tutorial.Person"    

#### Trying with a proto3 syntax document (see below).  Works with Python protobuf parsers
`pdir <- "~/DSwork/"`
`pfile <- file.path(pdir, "data-science.proto")`
`readProtoFiles(pfile)`
/Users/rtjohn/DSwork/data-science.proto:1:10:Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
Error in readProtoFiles(pfile) : 
  Could not load proto file '/Users/rtjohn/DSwork/data-science.proto'

**Comment by rtjohn** [comment]
syntax = "proto3";

package datascience;

// Represents a webpage through its HTML elements. For the most
// part, captures the following for the tags we're interested in:
// 1) An array of strings with the actual text content of the tag (innerHTML).
// 2) An integer count of the number of said tags present on the page.
// 3) Attribute values for some tags. The name of the attribute will be in the
// field. For instance, metaContent will be an array of string values
// representing the value of the content attribute for all <meta> tags.
message WebPageTagData {
  // Full text of the page
  string fullText = 1;

  repeated string a = 2;
  uint32 aCount = 3;
  repeated string p = 4;
  uint32 pCount = 5;
  repeated string imgSrc = 6;
  repeated string imgAlt = 7;
  uint32 imgCount = 8;
  repeated string h1 = 9;
  uint32 h1Count = 10;
  repeated string h2 = 11;
  uint32 h2Count = 12;
  repeated string h3 = 13;
  uint32 h3Count = 14;
  repeated string h4 = 15;
  uint32 h4Count = 16;
  repeated string h5 = 17;
  uint32 h5Count = 18;
  repeated string h6 = 19;
  uint32 h6Count = 20;
  repeated string div = 21;
  uint32 divCount = 22;
  repeated string span = 23;
  uint32 spanCount = 24;
  repeated string title = 25;
  uint32 titleCount = 26;
  repeated string li = 27;
  uint32 liCount = 28;

  // Tables
  uint32 tableCount = 29;
  repeated string th = 30;
  uint32 thCount = 31;
  repeated string td = 32;
  uint32 tdCount = 33;
  repeated string caption = 34;
  uint32 captionCount = 35;

  // Iframe html content will be appended to main tab's
  uint32 iframeCount = 36;
  repeated string metaContent = 37;
  uint32 metaCount = 38;
  repeated string button = 39;
  uint32 buttonCount = 40;
  uint32 scriptCount = 41;
  uint32 audioCount = 42;
  uint32 videoCount = 43;
  uint32 embedCount = 44;
  uint32 objectCount = 45;
  repeated string trackSrc = 46;
  uint32 trackCount = 47;

  // Forms
  uint32 formCount = 48;
  uint32 selectCount = 49;
  repeated string option = 50;
  uint32 optionCount = 51;
  repeated string inputValue = 52;
  uint32 inputCount = 53;
  repeated string textareaValue = 54;
  uint32 textareaCount = 55;
  repeated string label = 56;
  uint32 labelCount = 57;

  // HTML5 elements
  repeated string main = 58;
  uint32 mainCount = 59;
  repeated string header = 60;
  uint32 headerCount = 61;
  repeated string footer = 62;
  uint32 footerCount = 63;
  repeated string article = 64;
  uint32 articleCount = 65;
  repeated string dialog = 66;
  uint32 dialogCount = 67;
  repeated string section = 68;
  uint32 sectionCount = 69;
  repeated string nav = 70;
  uint32 navCount = 71;
  repeated string canvas = 72;
  uint32 canvasCount = 73;
}

**Comment by rtjohn** [comment]
Do you have a proto3 known to work with the package? I might try to see if it is my proto3 file or something else.

**Comment by eddelbuettel** [comment]
Yes, we did of course [add a unit test for proto3](https://github.com/eddelbuettel/rprotobuf/blob/master/inst/unitTests/runit.proto3.R) which uses [this proto3 file](https://github.com/eddelbuettel/rprotobuf/blob/master/inst/unitTests/data/proto3.proto).

Your example is more involved so maybe by bisecting we get a clearer idea of what is going on.

**Comment by eddelbuettel** [comment]
And just to cover the obvious bits: did you install RProtoBuf from source, so you know it used your v3 libraries?  Or could it be a macOS build that only saw v2?

```r
R> RProtoBuf:::getProtobufLibVersion()
[1] 3000000
R> 
```

**Comment by rtjohn** [comment]
Seems the obvious bits are the problem:

```
> RProtoBuf:::getProtobufLibVersion()
[1] 2006001
> 
```
Do you have a good resource for installing from source because produces the following error:

```
> install_github("eddelbuettel/rprotobuf")
Downloading GitHub repo eddelbuettel/rprotobuf@master
from URL https://api.github.com/repos/eddelbuettel/rprotobuf/zipball/master
Installing RProtoBuf
'/Library/Frameworks/R.framework/Resources/bin/R'  \
  --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/private/var/folders/34/7t1wjj055zz3sfs0mqys1tdc0000gn/T/RtmplH1VyB/devtoolsb336fe93840/eddelbuettel-rprotobuf-ff252da'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘RProtoBuf’ ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for pkg-config... no
checking for protoc... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking google/protobuf/stubs/common.h usability... no
checking google/protobuf/stubs/common.h presence... no
checking for google/protobuf/stubs/common.h... no
configure: WARNING: Protobuf headers not found with default CXXFLAGS and CPPFLAGS, manually trying /usr/local/include
configure: WARNING: Unsetting ac_cv_header_google_protobuf_stubs_common_h
checking google/protobuf/stubs/common.h usability... no
checking google/protobuf/stubs/common.h presence... no
checking for google/protobuf/stubs/common.h... no
configure: error: ERROR: ProtoBuf headers required; use '-Iincludedir' in CXXFLAGS for unusual locations.
ERROR: configuration failed for package ‘RProtoBuf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RProtoBuf’
Installation failed: Command failed (1)
```

**Comment by rtjohn** [comment]
Got it to work.
Seems installing protoc from:
https://github.com/google/protobuf/releases

And following these instructions:
https://github.com/google/protobuf/releases

Breaks things during the Rprotobuf install on Mac OS.

Instead just use Home Brew to install:
```
$ brew install protobuf
$ brew link --overwrite protobuf
```
The last line was necessary only because I had done the prior install attempt.

Once protobuf was installed via Brew I ran as normal:
```
library(devtools)
install_github("eddelbuettel/rprotobuf")
> RProtoBuf:::getProtobufLibVersion()
[1] 3005001
```

**Comment by eddelbuettel** [comment]
Yay!  Excellent news.  

I'll close this then.
