### ISSUE TITLE
Problems serializing R POSIXlt objects

### ISSUE THREAD

**Issue by jefshe** [eddelbuettel/rprotobuf#47]
I ran into an issue recently when using rprotobuf to serialize then deserialize a POSIXlt object:
```
library(RProtoBuf)
obj <- as.POSIXlt(Sys.time())
unserialize_pb(serialize_pb(obj, connection=NULL))
```
yields the following error:
```
Error in attributes(xobj) <- attrib[names(attrib) != "class"] : 
  'names' attribute [11] must be the same length as the vector [1]
```

what's happening is that the POSIXlt object is represented as a list of attributes in R e.g. (hours, min, sec...) but when iterated over using lapply it appears only to be a list of length 1. Only by unclassing the object do we see its true representation:
```
> obj
[1] "2018-08-23 16:48:29 AEST"
> unclass(obj)
$`sec`
[1] 29.09264

$min
[1] 48

$hour
[1] 16

$mday
[1] 23
...
```

this somewhat related to https://github.com/eddelbuettel/rprotobuf/issues/37 which had a similar issue where the list access had special handling for a particular class of object.

I propose that prior to serializing lists in the package we unclass the object beforehand

**Comment by eddelbuettel** [comment]
That may be more a known issue with `POSIXlt` as well.  

You could address it on your side by focusing `POSIXct`, the compat representation:

```
R> library(RProtoBuf)
R> obj <- as.POSIXct(Sys.time())
R> unserialize_pb(serialize_pb(obj, connection=NULL))
[1] "2018-08-23 05:06:55.263143 CDT"
R> 
```

Also:

```
R> now <- as.POSIXlt(Sys.time())
R> identical(as.POSIXlt(unserialize_pb(serialize_pb(as.POSIXct(now), connection=NULL))), now)
[1] TRUE
R> 
```

**Comment by eddelbuettel** [comment]
@jefshe I would appreciate some followup on this as the related #48 which I still find to encompassing.

I plan to close this unless I hear from you.

**Comment by jefshe** [comment]
Sorry for not following up soon @eddelbuettel , that's fair. My main motivation was encountering this issue before in #37 as well. I doubt these 2 are isolated cases.
 
I do agree it's a big change. Would a more narrow condition, like checking if unclassing the list changes the value of the list be more appropriate?

**Comment by eddelbuettel** [comment]
Well, one step at a time.  #37 is closed, and if there was an issue, wasn't it with `as.raw()` which is base R?

As for falling over `POSIXlt`:  how about if you rework your PR to
- not blindly move away from the existing `if`/`else`
- find in which branch _your_ error occurs
- test for `POSIXlt` and if true `unclass`

That would be a bit more surgical.  And should overcome the issue while not changing things for everybody else.

**Comment by jefshe** [comment]
Okay I'm happy to make that change, I've updated the PR now.

The issue with #37 was that calling `lapply` on a `package_version` object had unexpected behaviour similar to this scenario. I take your point however, and have just added a fix for this specific scenario

**Comment by eddelbuettel** [comment]
That looks better, and is more minimal.

**Comment by eddelbuettel** [comment]
@jeroen Can you take a quick at #48?  Just changing in `rexp_list()` when a POSIXlt is seen should be fine, address the issue and not have side effects.

**Comment by eddelbuettel** [comment]
I still find it a little broad.  But the dispatching from `rexp_obj.R` and its `rexp_obj()` in

```r
  msg <- switch(sm,
    "character" = rexp_string(obj),
    "raw" = rexp_raw(obj),
    "double" = rexp_double(obj),
    "complex" = rexp_complex(obj),
    "integer" = rexp_integer(obj),
    "list" = rexp_list(obj),
    "logical" = rexp_logical(obj),
    "NULL" = rexp_null(),
    return(rexp_native(obj))
  );
```

via `rexp_list` seems fine as we now check the list elements.   I think I'll merge this.

**Comment by eddelbuettel** [comment]
#48 is merged so closing.  

Thanks for the PR!
