### ISSUE TITLE
Support reading multiple protobuf messages from a single file

### ISSUE THREAD

**Issue by SergeySandler** [eddelbuettel/rprotobuf#52]
See the following code fragment,

```r
library(RProtoBuf)
readProtoFiles(package = "RProtoBuf")

p1 <- new(tutorial.Person, name = "Romain", id = 1)
p2 <- new(tutorial.Person, name = "John", id = 2)

tf <- tempfile()
con <- file(tf, open = "wb")
p1$serialize(con)
p2$serialize(con)
close(con)

rawData <- readBin(tf, raw(0), n=file.size(tf))
msg <- RProtoBuf::read(tutorial.Person, rawData)
as.character(msg)   # this is p2
```

My expectation was the msg represents p1, not p2. Then, I'd read the next element from 
`rawData[(msg$bytesize()+1) : file.size(tf)]` .

The things become even more inconsistent when there is a mix of different messages in a protobuf file.
In my understanding, multiple messages in a single protobuf file is a common practice, fully supported in at least C++.

**Comment by SergeySandler** [comment]
After doing more research, this feature is not available _off-the-shelf_ form the protobuf library and requires a custom implementation, see _Streaming Multiple Messages_ in https://developers.google.com/protocol-buffers/docs/techniques#streaming .
Not sure if it is a good idea extending RProtoBuf to facilitate the feature. This should be easy to implement this feature as required in a custom R code.

**Comment by eddelbuettel** [comment]
Given that this got stale without an actual follow-up I will close it now.
