### ISSUE TITLE
testthat::expect_identical() fails when comparing two identical Messages

### ISSUE THREAD

**Issue by jarodmeng** [eddelbuettel/rprotobuf#55]
This issue is similar to #53, but require a slightly different fix.

The root cause is that `testthat::expect_identical()` and `RUnit::checkIdentical()` call `identical()` to compare the two testing objects. `identical()` is not a S3 generic and the two packages don't define a S4 generic on `identical()`. As a result, when `identical()` is called in `expect_identical()` or `checkIdentical()`, R simply uses `base::identical()` rather than search for a proper dispatch. However, `base::identical()` returns FALSE for two Messages with the same content (probably because despite having the same content, the two Messages have different external pointers) and thus incorrectly fails the test.

Unlike #53 that can be fixed by #54 through adding a S3 dispatch in `RProtoBuf`, this issue needs to be fixed in `testthat` and `RUnit` packages. Specifically, they need to declare `identical()` a generic function so that a call to `identical()` would properly dispatch based on argument types. I will raise an issue in `testthat` and `RUnit` on this, but want to create a thread here in `RProtoBuf` to explain the context. No action is needed from `RProtoBuf`.

``` r
library(RProtoBuf)
library(testthat)
library(RUnit)

# Create two Message objects that have the same descriptor and content
p <- new(tutorial.Person, name = "John", id = 1)
p2 <- new(tutorial.Person, name = "John", id = 1)

# Calling identical() directly finds RProtoBuf's dispatch and returns TRUE
identical(p, p2)
#> [1] TRUE

# identical() from base package returns FALSE
base::identical(p, p2)
#> [1] FALSE

# expect_identical() is using base::identical and fails the test
expect_identical(p, p2)
#> Error: `p` not identical to `p2`.
#> Objects equal but not identical

# checkIdentical() is using base::identical too
checkIdentical(p, p2)
#> Error in checkIdentical(p, p2): FALSE 
```

<sup>Created on 2018-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by eddelbuettel** [comment]
Well reasoned.  The counter-argument might be that these are custom (S4) objects so maybe users should always resort to using `identical(...)` and checking for `TRUE`?

**Comment by eddelbuettel** [comment]
Closing as not really us here.
