### ISSUE TITLE
Can RProtoBuf package be installed on linux

### ISSUE THREAD

**Issue by Elbuort-Lee** [eddelbuettel/rprotobuf#60]
Can RProtoBuf package be installed on linux

**Comment by eddelbuettel** [comment]
Of course.  See the check status: https://cloud.r-project.org/web/checks/check_results_RProtoBuf.html

**Comment by Elbuort-Lee** [comment]
hi,buddy from afar; can you help me solve the problem I encountered in installing RProtoBuf on centos?
![5609e2f3f09abd6a3c2773e817502d8](https://user-images.githubusercontent.com/42463860/65492280-3767c200-dee3-11e9-870d-3e7cc56e4907.png)

**Comment by eddelbuettel** [comment]
You need help on CentOS installation of _Protocol Buffer_ which are a _prerequisite_ of install RProtoBuf.  I cannot help you installing that library.

But we also provide working Docker images.

**Comment by Elbuort-Lee** [comment]
Thank you for your advice. perfect

**Comment by Elbuort-Lee** [comment]
hi，I've been using Rcpp recently. I'd like to ask Rcpp R CMD SHLIB Link multiple C++ files to xxx.so file. For example, R CMD SHLIB temp.cpp hello.cpp. Is this ok?
