### ISSUE TITLE
Feature request: implement messageToJson

### ISSUE THREAD

**Issue by botanize** [eddelbuettel/rprotobuf#61]
The python protobuf package easily converts a message into a json implementation. See https://developers.google.com/protocol-buffers/docs/reference/python/

The RProtoBuf functions `toString` and `as.character` create text representations that look like JSON, but aren't (they're mostly missing commas and quotes). I think it would be wonderful to have a fast C implementation of this, especially as the `as.list` function doesn't work recursively.

**Comment by eddelbuettel** [comment]
Sure. Can you volunteer an implementation?

**Comment by botanize** [comment]
Unfortunately I have very little experience with c and none with c++.  The best I could do would be to attempt to reformat the `as.character` output with grep pattern replacements. But I don't think that's a good idea.

**Comment by eddelbuettel** [comment]
No we'd need someone with a few spare hours, interest and and enough knowledge to export the function in that third link I showed.  I'll add a 'help wanted' label but I won't have time in the near future.

**Comment by eddelbuettel** [comment]
A big BIG _BIG_ Thank You! to @siddharthab for making it happen.  Soon to be on a CRAN mirror near you.

**Comment by siddharthab** [comment]
> A big BIG _BIG_ Thank You! to @siddharthab for making it happen. Soon to be on a CRAN mirror near you.

Just trying to keep promises I made long ago. 😄 
https://github.com/eddelbuettel/rprotobuf/issues/6#issuecomment-144181324

**Comment by eddelbuettel** [comment]
Hah! That was indeed a long(ish) time ago!
