### ISSUE TITLE
gRPC client

### ISSUE THREAD

**Issue by yimyom** [eddelbuettel/rprotobuf#69]
Where to find or which package to use to write a gRPC client? I know there is https://github.com/nfultz/grpc but it has quite a few bugs and after fixing functions after functions I gave up.

Any suggestions? Did I miss something in RProtoBuf?

**Comment by eddelbuettel** [comment]
I love gRPC as well but it has a lot of extra dependencies -- which is why @nfultz went the Docker route (last time I checked, which was a while ago).  

Strictly speaking this is also not an RProtoBuf issue -- nothing promised by RProtoBuf is failing, breaking or missing -- but "simply" a desire to have another (arguably complicated) package.  So I suggest we close this here.

**Comment by nfultz** [comment]
You can also just generate  grpc stubs in C++ using Google's tooling, and run those using Rcpp.

**Comment by yimyom** [comment]
Thanks @eddelbuettel and @nfultz for your comments. 
Ideally, I would prefer to be able to use a nice R package instead of generating C++ stubs. In my current context, the grpc makes much more sense as having those C++ stubs in Rcpp (which I love anway) wouldn't be practical.
I'll take the discussion now to nfultz/grpc and try to contribute improvements to this package.

**Comment by eddelbuettel** [comment]
Keep me posted for possible help from here, and  general interest in promoting gRPC.

**Comment by dlong11** [comment]
@nfultz do you happen to have an example that uses the C++ stub in an R package?  I am having an issue compiling the stubs.

**Comment by nfultz** [comment]
@dlong11 Unfortunately I don't, but if you get it working please share it so we can learn from it. You might try using building stubs for the simple greeter service from the tutorials first - https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto and see if that works before trying more complicated services.

**Comment by dlong11** [comment]
@nfultz Will do. I am doing exactly what you described.  Trying to get the simple version working.  I am  getting further, but I am running into a few undefined references.  Like  
```
google::protobuf::internal::InlineGreedyStringParser(std::string*, char const*, google::protobuf::internal::ParseContext*)
google::protobuf::internal::fixed_address_empty_string
google::protobuf::MessageLite::InitializationErrorString()
```
I verified that I am using the correct libprotobuf-lite but I am still seeing these.   I will investigate further.
