### ISSUE TITLE
Sample code to write "descrition" class objects in the demo. 

### ISSUE THREAD

**Issue by hansthompson** [eddelbuettel/rprotobuf#7]
I'm about to dive into making a protocol buffer to put our bus on google real-time transit and I wanted to check something with you quickly before I start down the wrong path.  

I want to use RProtoBuf to write out my finished .pb files and I have a .proto file template that google provides however, I don't see in your tutorial how to create a Descriptor class objects for my own purpose.  I've cloned the RProtoBuf repo and I'm about to dig into writing my own descriptor object but if it possible would you be able to show me how you would write a very simple descriptor?  If you only have a small amount of time I'll offer to  contribute to the demos for the package to include what I learn about it for future users.

**Comment by eddelbuettel** [comment]
For this project, `proto` files are typically seen as "fixed" input.  Am I understanding you correctly as desiring to _create_ proto files?  That is not what we do here.

**Comment by hansthompson** [comment]
I don't think I described my situation well the first time.  

I want to use different .protofiles than the ones provided in the package and I can't tell how objects like tutorial.person are created or where they are loaded from to gain insight into using this package to bind from existing .proto files from google. 

I would like to be able to write a protocol buffer to this specification:

https://developers.google.com/transit/gtfs-realtime/examples/trip-updates-full

And there is a template .proto here 

https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto

Is there a way to make an equivalent object for this gtfs-realtime.proto like tutorial.Person is for it's .proto? And does this package handle that or is it only intended for the included templates? I don't see that documented but this package is different than I am used to and I'm still learning.

**Comment by eddelbuettel** [comment]
Seems to work just fine:

```r
R> library(RProtoBuf)
R> download.file("https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto", "/tmp/gtfs-realtime.proto")
trying URL 'https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto'
Content type 'text/plain; charset=utf-8' length 27095 bytes (26 KB)
==================================================
downloaded 26 KB

R> readProtoFiles("/tmp/gtfs-realtime.proto")
R> P("transit_realtime.FeedMessage")
descriptor for type 'transit_realtime.FeedMessage' 
R> fh <- new(transit_realtime.FeedMessage)
R> fh
message of type 'transit_realtime.FeedMessage' with 0 fields set
R> 
```

You would have to set fields etc for a real object. I leave that to you...

**Comment by hansthompson** [comment]
Thanks! That gives me enough to use it now. I could not find any reference to using P until you described it here.

**Comment by eddelbuettel** [comment]
There is a link / See also entry in `readProtoFiles()`.
