### ISSUE TITLE
Latest release (0.4.18) requires protobuf 3.3.0 or later

### ISSUE THREAD

**Issue by kyleam** [eddelbuettel/rprotobuf#83]
The `SystemRequirements` field in `DESCRIPTION` says that "ProtoBuf libraries and compiler version 2.2.0 or later" are required.  However, commit e1e30c6 (Add extra parameters to toJSON method, 2021-06-10) from the 0.4.18 release refers to `preserve_proto_field_names`.  This option was added in protobuf's 89eb4e51b (Add option to preserve original proto field names, 2017-03-17), which was first included in protobuf's v3.3.0 release.

If I run `R CMD build .` with the latest commit in this repo (eac14e3) on a system with Protobuf 3.0.0 (`apt-cache policy` at end of post), I see the following failure:

```
[...]
g++ -std=gnu++11 -I"/opt/R/4.1.1/lib/R/include" -DNDEBUG -pthread -g -O2 -pthread -I'/opt/rpkgs/4.1/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c wrapper_Message.cpp -o wrapper_Message.o
wrapper_Message.cpp: In function ‘Rcpp::CharacterVector rprotobuf::Message__as_json__rcpp__wrapper__(Rcpp::XPtr<google::protobuf::Message>, bool, bool)’:
wrapper_Message.cpp:453:10: error: ‘struct google::protobuf::util::JsonPrintOptions’ has no member named ‘preserve_proto_field_names’
     opts.preserve_proto_field_names = preserve_proto_field_names;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/R/4.1.1/lib/R/etc/Makeconf:177: recipe for target 'wrapper_Message.o' failed
make: *** [wrapper_Message.o] Error 1
ERROR: compilation failed for package ‘RProtoBuf’
* removing ‘/tmp/RtmpckMgdG/Rinst74964a128b31/RProtoBuf’
      -----------------------------------
ERROR: package installation failed
```

Going back to the parent of e1e30c6 (5615e94), `R CMD build .` succeeds.

Based on reviewing the discussion in the associated gh-79, I think introducing this incompatibility was unintentional, though at the very least it seems like the `SystemRequirements` description should be updated.

Thanks for taking a look.

<details>
<summary>apt-cache policy output</summary>

```
$ apt-cache policy libprotoc-dev libprotobuf-dev protobuf-compiler
libprotoc-dev:
  Installed: 3.0.0-9.1ubuntu1
  Candidate: 3.0.0-9.1ubuntu1
  Version table:
 *** 3.0.0-9.1ubuntu1 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
libprotobuf-dev:
  Installed: 3.0.0-9.1ubuntu1
  Candidate: 3.0.0-9.1ubuntu1
  Version table:
 *** 3.0.0-9.1ubuntu1 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
protobuf-compiler:
  Installed: 3.0.0-9.1ubuntu1
  Candidate: 3.0.0-9.1ubuntu1
  Version table:
 *** 3.0.0-9.1ubuntu1 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

</details>

**Comment by eddelbuettel** [comment]
Thanks for taking the time to write a ticket.  

A few of the more recent updates did in fact come from users of current versions of Protocol Buffers.  In general, we are of the view that 'current is best'.  So you should not assume this will run on any random old distribution version with their old Protocol Buffers library -- ProtoBuf 3.0 is from [July 2016 per this release tag](https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.0).  

Now, I work on Ubuntu too but at time create backports as needed.  Currently I seem to have the Ubuntu distro version (which is 3.12.4 for me under 21.04)  but I have at time backported.  I can see 3.0.0 in my [ppa:edd/misc](https://launchpad.net/~edd/+archive/ubuntu/misc) for xenial and trusty. 

A second look at [Ubuntu's packaging page for `libprotobuf-dev`](https://packages.ubuntu.com/search?keywords=libprotobuf-dev&searchon=names&suite=all&section=all) reveals that this really only bites on Ubuntu 18.04.  So ... this really sounds like your problem by insisting on the soon-to-be-four-year-old-twice-replaced LTS release.  I strongly recommend 20.04 (but you may have local/institutional reasons to remain).

So going forward, I see three ways:
- you need a newer ProtocolBuffers library; there is no reason to be stuck at 3.0.0; I may be able to help (esp if you become more specific as to _what_ system you run on)
- if you cannot upgrade or do not want to you can simply run an older version of the R package
- if that does not suit you could propose a clean pull request to accomodate your older library by `#ifdef`ing it; as this is a fairly specialised need for your situation I do not think I am very likely to work on it

I can definitely update the text in SystemRequirements.  As you may know, this is informal at CRAN and non-binding.

**Comment by eddelbuettel** [comment]
Thanks for the added detail.  At our end it really is easiest to state that 3.3.0 is the minimally required version.  As it is now almost five years old this is not too onerous.

If you want, I can probably fetch the version from focal and send it to my PPA which would give you an amd64 binary package set for bionic (provided it builds without other changes, sometimes build-dependencies get in the way).   If we really must we can probably isolate the change for JSON params and make it a nullop under conditioning but I would need you to lead that as I cannot test on the older setup (as easily).

**Comment by kyleam** [comment]
> So ... this really sounds like your problem by insisting on the soon-to-be-four-year-old-twice-replaced LTS release.

Yes, it is.  Apologies if my post read as though I expected you to support such an old version.  My decision to report the build failure was very much based on what DESCRIPTION described as the minimally supported version.  Thank you for updating it.

**Comment by eddelbuettel** [comment]
No -- thank you again for bringing it up.  The docs should reflect that, and I was likely unaware the JSON feature made us depend on 3.3.0 or later.

I assume you can now help yourself to a working setup via any of the discussed routes?  Let me know if I can help some more, but as discussed, this volunteer project prefers, just like others, to work reliably with _current_ versions of components.  We don't have the bandwidth for full cross products of release and depencencies....
