### ISSUE TITLE
Package required but not available: ‘RProtoBuf’ - Oracle Solaris 10, x86, 32 bit, R-release

### ISSUE THREAD

**Issue by vamshimupparaju** [eddelbuettel/rprotobuf#84]
Hi Team,

Hope you are doing well !!

One of my R package depends upon '**RProtobuf**' when I am trying to test my package on rhub "**https://builder.r-hub.io/**"  receiving the error notification as - "**Package required but not available: ‘RProtobuf’** ".

Can you please confirm whether RProtobuf supports Solaris Platform ?

Thanks in Advance.

**Comment by eddelbuettel** [comment]
I don't know but I'd say "likely" if and when someone builds the Protocol Buffers library there first.  See the SystemRequirements for what it take.  

We don't have access to such a system and primarily aim for what we can support via CRAN so I am closing this.  Happy to discuss PRs if you have a system where you can tests them.
