### ISSUE TITLE
compilation failure on Alpine 3.19

### ISSUE THREAD

**Issue by bastistician** [eddelbuettel/rprotobuf#95]
**RProtoBuf** fails to install on brand-new Alpine Linux 3.19.0 (with GCC 13.2, using the musl libc):
```
g++ -std=gnu++17 -I"/usr/include/R" -DNDEBUG -DPROTOBUF_USE_DLLS -DNOMINMAX -O2 -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt -D__MUSL__ -flto -DPROTOBUF_USE_DLLS -DNOMINMAX -I'/usr/lib/R/library/Rcpp/include'     -fpic  -O2 -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt -D__MUSL__ -flto -c DescriptorPoolLookup.cpp -o DescriptorPoolLookup.o
DescriptorPoolLookup.cpp:36:13: error: cannot declare variable 'rprotobuf::DescriptorPoolLookup::source_tree' to be of abstract type 'rprotobuf::RSourceTree'
   36 | RSourceTree DescriptorPoolLookup::source_tree;
      |             ^~~~~~~~~~~~~~~~~~~~
In file included from DescriptorPoolLookup.h:7,
                 from DescriptorPoolLookup.cpp:22:
RSourceTree.h:5:7: note:   because the following virtual functions are pure within 'rprotobuf::RSourceTree':
    5 | class RSourceTree : public GPB::compiler::SourceTree {
      |       ^~~~~~~~~~~
In file included from rprotobuf.h:37,
                 from DescriptorPoolLookup.cpp:21:
/usr/include/google/protobuf/compiler/importer.h:248:36: note:     'virtual google::protobuf::io::ZeroCopyInputStream* google::protobuf::compiler::SourceTree::Open(absl::lts_20230802::string_view)'
  248 |   virtual io::ZeroCopyInputStream* Open(absl::string_view filename) = 0;
      |                                    ^~~~
make: *** [/usr/lib/R/etc/Makeconf:200: DescriptorPoolLookup.o] Error 1
ERROR: compilation failed for package ‘RProtoBuf’
```

Here is a minimal Dockerfile to reproduce:
```Dockerfile
FROM alpine:3.19
ENV TZ=UTC
RUN apk add --no-cache R R-doc R-dev g++ protobuf-dev
RUN R -s -e 'install.packages("RProtoBuf", repos = "https://cloud.R-project.org/")'
```

**Comment by eddelbuettel** [comment]
Ok, I can replicate that.  I suspect you have to (explicitly) stick with an older ProtoBuf liibrary (and/or adjust the code).

I may not have time to work on that.  Contributions welcome.

**Comment by eddelbuettel** [comment]
I am more less _four pages in_ on the ]Releases for ProtoBuf](https://github.com/protocolbuffers/protobuf/releases?page=4) before I find [the version Debian has](https://packages.debian.org/search?keywords=libprotobuf-dev&searchon=names&suite=all&section=all).  If something moves this fast upstream we are not guaranteed to be able to help.  The change may be simple, it will eventually hit people inside Google too from where the last few pull requests came (which were all excellent and narrowly focussed).  So in short if you need this _now_ on _those Alpine versions_ you may have to roll up your sleeves.

**Comment by bastistician** [comment]
Thanks. I now see that my report is actually a duplicate of #92, which has an open PR. I'll check if applying that patch fixes the installation for me.

**Comment by eddelbuettel** [comment]
Oh, dang, I am the one who should have remembered!  Yes trying / extending that is likely the best course of action.

**Comment by eddelbuettel** [comment]
It looks like I slept a little / hesitated a little on #93 by @TeoGiane -- but given that you actually demonstrate viability in a container we _do_ have a path format in getting the patch in along with a simple container.  See e.g. this [yaml file](https://github.com/eddelbuettel/RcppInt64/blob/master/.github/workflows/r2u.yaml) from the repo I updated this morning following your other ticket: while it uses the [r2u](https://eddelbuettel.github.io/r2u) for easy + fast + reliable binaries under Ubuntu, we could use the same pattern of dropping into the `alpine:3.19` container and execute your commands above for installation. That would give us reproducibility here.

**Comment by eddelbuettel** [comment]
Taken care of by #93
