### ISSUE TITLE
Use `toTextFormat()` for serializing protobufs, rather than `as.character` or `toString()`.

### ISSUE THREAD

**Issue by tanx16** [eddelbuettel/rprotobuf#98]
The RProtoBuf implementation depends on C++ Protobuf, which is changing DebugString output in the future. Due to this change, RProtoBuf stringifying APIs (toString(), as.character()) will no longer be parseable. Use `toTextFormat()` instead.

**Comment by eddelbuettel** [comment]
Thanks for the heads-up.  Would you be able to provide a PR ?
